# Clean Data part - by Weitong Cai

## Clean First Dataset as Netflix Movie from 2011 to 2021

In [1]:
import os
import csv
import pandas as pd

#Read First csv file path: the netflix_titles
netflix_df = pd.read_csv("Resources/netflix_titles.csv")
netflix_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [2]:
#Take only the movie from the type column, we don't need TV show for our project
netflix_movie_df=netflix_df[netflix_df["type"] == "Movie"]
netflix_movie_df = netflix_movie_df.reset_index()
netflix_movie_df.head()

,index,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
2,7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
3,9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
4,12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niew√∂hner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...

In [3]:
#Take the columns that are useful for our project question
clean_movie_df = netflix_movie_df[["show_id","title", "director", "country", "release_year", "rating", "duration","listed_in","type"]]

#Rename the columns
clean_movie_df = clean_movie_df.rename(columns = {"show_id" : "Show_ID",
                                                  "title": "Movie Title",
                                                  "director": "Director",
                                                  "country": "Country",
                                                  "release_year":"Release_Year",
                                                  "rating" : "Rating_class",
                                                  "duration" : "Duration",
                                                  "listed_in" : "Categories",
                                                  "type" : "Type",})
print(clean_movie_df.index)
print(clean_movie_df.columns)

clean_movie_df.head(10)

RangeIndex(start=0, stop=6131, step=1)
Index(['Show_ID', 'Movie Title', 'Director', 'Country', 'Release_Year',
       'Rating_class', 'Duration', 'Categories', 'Type'],
      dtype='object')

,Show_ID,Movie Title,Director,Country,Release_Year,Rating_class,Duration,Categories,Type
0,s1,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90 min,Documentaries,Movie
1,s7,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha",NaN,2021,PG,91 min,Children & Family Movies,Movie
2,s8,Sankofa,Haile Gerima,"United States, Ghana, Burkina Faso, United Kin...",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies",Movie
3,s10,The Starling,Theodore Melfi,United States,2021,PG-13,104 min,"Comedies, Dramas",Movie
4,s13,Je Suis Karl,Christian Schwochow,"Germany, Czech Republic",2021,TV-MA,127 min,"Dramas, International Movies",Movie
5,s14,Confessions of an Invisible Girl,Bruno Garotti,NaN,2021,TV-PG,91 min,"Children & Family Movies, Comedies",Movie
6,s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave Garc√≠a, Pablo Azor√≠n Williams",NaN,2020,TV-MA,67 min,"Documentaries, International Movies",Movie
7,s19,Intrusion,Adam Salky,NaN,2021,TV-14,94 min,Thrillers,Movie
8,s23,Avvai Shanmughi,K.S. Ravikumar,NaN,1996,TV-PG,161 min,"Comedies, International Movies",Movie
9,s24,Go! Go! Cory Carson: Chrissy Takes the Wheel,"Alex Woo, Stanley Moore",NaN,2021,TV-Y,61 min,Children & Family Movies,Movie

In [6]:
#Our project only need data period 2011-2021.
year_netflix_df= clean_movie_df[clean_movie_df["Release_Year"].isin([2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021])]
final_netflix_df=year_netflix_df.reset_index()
del final_netflix_df["index"]
final_netflix_df.head()

,Show_ID,Movie Title,Director,Country,Release_Year,Rating_class,Duration,Categories,Type
0,s1,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90 min,Documentaries,Movie
1,s7,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha",NaN,2021,PG,91 min,Children & Family Movies,Movie
2,s10,The Starling,Theodore Melfi,United States,2021,PG-13,104 min,"Comedies, Dramas",Movie
3,s13,Je Suis Karl,Christian Schwochow,"Germany, Czech Republic",2021,TV-MA,127 min,"Dramas, International Movies",Movie
4,s14,Confessions of an Invisible Girl,Bruno Garotti,NaN,2021,TV-PG,91 min,"Children & Family Movies, Comedies",Movie

In [7]:
#Check the type of each column to make sure if "Release_Year" and "Duration" as number
#There are 'NaN' in column "Moive Title", "Director" and "Duration"

print(final_netflix_df.dtypes)

Show_ID         object
Movie Title     object
Director        object
Country         object
Release_Year     int64
Rating_class    object
Duration        object
Categories      object
Type            object
dtype: object

In [8]:
#Transfer the "Duration" from string to integer, if the column = 'NaN', then consider it as integer 0
import numpy as np
final_netflix_df["Duration"] =final_netflix_df["Duration"].str.split().str[0]
final_netflix_df["Duration"] = final_netflix_df["Duration"].apply(lambda x: int(x) if not np.isnan(float(x)) else 0)
print(final_netflix_df.dtypes)

Show_ID         object
Movie Title     object
Director        object
Country         object
Release_Year     int64
Rating_class    object
Duration         int64
Categories      object
Type            object
dtype: object

In [9]:
# Final data frame for Netflix Moive
final_netflix_df

,Show_ID,Movie Title,Director,Country,Release_Year,Rating_class,Duration,Categories,Type
0,s1,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90,Documentaries,Movie
1,s7,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha",NaN,2021,PG,91,Children & Family Movies,Movie
2,s10,The Starling,Theodore Melfi,United States,2021,PG-13,104,"Comedies, Dramas",Movie
3,s13,Je Suis Karl,Christian Schwochow,"Germany, Czech Republic",2021,TV-MA,127,"Dramas, International Movies",Movie
4,s14,Confessions of an Invisible Girl,Bruno Garotti,NaN,2021,TV-PG,91,"Children & Family Movies, Comedies",Movie
...,...,...,...,...,...,...,...,...,...
4819,s8792,Young Adult,Jason Reitman,United States,2011,R,94,"Comedies, Dramas, Independent Movies",Movie
4820,s8795,ÿßÿ¥ÿ™ÿ®ÿßŸÉ,Mohamed Diab,"Egypt, France",2016,TV-14,98,"Dramas, Independent Movies, International Movies",Movie
4821,s8799,Zed Plus,Chandra Prakash Dwivedi,India,2014,TV-MA,131,"Comedies, Dramas, International Movies",Movie
4822,s8802,Zinzana,Majid Al Ansari,"United Arab Emirates, Jordan",2015,TV-MA,96,"Dramas, International Movies, Thrillers",Movie
4823,s8807,Zubaan,Mozez Singh,India,2015,TV-14,111,"Dramas, International Movies, Music & Musicals",Movie

In [19]:
#Save the cleaned data for future analysis
final_netflix_df.to_csv('Clean_Netflix_Movie.csv', index=False)

## 2. Clean the Second Dataset and merge with First Dataset

In [11]:
#Read First csv file path
rating_df = pd.read_csv("Resources/titles.csv")
rating_df.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN,0.600,NaN
1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7

In [12]:
netflix_rating_df=rating_df[rating_df["type"] == "MOVIE"]
netflix_rating_df = netflix_rating_df.reset_index()
netflix_rating_df.head(5)

,index,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,1,tm84618,Taxi Driver,MOVIE,A mentally unstable Vietnam War veteran works ...,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0,27.612,8.2
1,2,tm127384,Monty Python and the Holy Grail,MOVIE,"King Arthur, accompanied by his squire, recrui...",1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0,18.216,7.8
2,3,tm70993,Life of Brian,MOVIE,"Brian Cohen is an average young Jewish man, bu...",1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0,17.505,7.8
3,4,tm190788,The Exorcist,MOVIE,12-year-old Regan MacNeil begins to adapt an e...,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0,95.337,7.7
4,6,tm14873,Dirty Harry,MOVIE,When a madman dubbed 'Scorpio' terrorizes San ...,1971,R,102,"['thriller', 'crime', 'action']",['US'],NaN,tt0066999,7.7,153463.0,14.745,7.5

In [13]:
year_rating_df= netflix_rating_df[netflix_rating_df["release_year"].isin([2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021])]
year_rating_df=year_rating_df.reset_index()
del year_rating_df["index"]
year_rating_df.head()

,level_0,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,543,tm170758,Hop,MOVIE,"E.B., the Easter Bunny's teenage son, heads to...",2011,PG,95,"['comedy', 'fantasy', 'animation', 'family']",['US'],NaN,tt1411704,5.4,33734.0,12.008,5.7
1,544,tm166064,"Crazy, Stupid, Love.",MOVIE,Cal Weaver is living the American dream. He ha...,2011,PG-13,118,"['romance', 'comedy', 'drama']",['US'],NaN,tt1570728,7.4,507878.0,30.363,7.3
2,545,tm170442,Margin Call,MOVIE,A thriller that revolves around the key people...,2011,R,107,"['thriller', 'drama']",['US'],NaN,tt1615147,7.1,125883.0,17.311,6.8
3,546,tm41792,Django Unchained,MOVIE,"With the help of a German bounty hunter, a fre...",2012,R,165,"['western', 'drama']",['US'],NaN,tt1853728,8.4,1472668.0,56.588,8.1
4,547,tm50018,Looper,MOVIE,"In the futuristic action thriller Looper, time...",2012,R,119,"['thriller', 'scifi', 'drama', 'crime', 'action']",['US'],NaN,tt1276104,7.4,566791.0,48.347,6.9

In [14]:
clean_rating_df = year_rating_df[["title", "imdb_score", "imdb_votes"]]
clean_rating_df = clean_rating_df.rename(columns = {"title" : "Movie Title",
                                                   "imdb_score" : "IMDB_Score",
                                                   "imdb_votes" : "IMDB_Votes"})

clean_rating_df.head()

            Movie Title  IMDB_Score  IMDB_Votes
0                   Hop         5.4     33734.0
1  Crazy, Stupid, Love.         7.4    507878.0
2           Margin Call         7.1    125883.0
3      Django Unchained         8.4   1472668.0
4                Looper         7.4    566791.0

In [15]:
#Check the type of each column to 
#If there are 'NaN' in column "IMDB_Score"and "IMDB_Votes", then consider as 0

print(clean_rating_df.dtypes)

Movie Title     object
IMDB_Score     float64
IMDB_Votes     float64
dtype: object

In [16]:
#Save the clean data frame as 'Netflix_Rating.csv'
clean_rating_df.to_csv("Netflix_Rating.csv", index=False)

## Merge the two data set and save as 'Merged_Netflix_movie&rating.csv'

In [17]:

title_rating_df = pd.merge(final_netflix_df, clean_rating_df, on = ["Movie Title"] , how = "inner")
title_rating_df

,Show_ID,Movie Title,Director,Country,Release_Year,Rating_class,Duration,Categories,Type,IMDB_Score,IMDB_Votes
0,s1,Dick Johnson Is Dead,Kirsten Johnson,United States,2020,PG-13,90,Documentaries,Movie,7.4,6390.0
1,s7,My Little Pony: A New Generation,"Robert Cullen, Jos√© Luis Ucha",NaN,2021,PG,91,Children & Family Movies,Movie,6.8,3468.0
2,s10,The Starling,Theodore Melfi,United States,2021,PG-13,104,"Comedies, Dramas",Movie,6.3,11733.0
3,s14,Confessions of an Invisible Girl,Bruno Garotti,NaN,2021,TV-PG,91,"Children & Family Movies, Comedies",Movie,5.2,966.0
4,s19,Intrusion,Adam Salky,NaN,2021,TV-14,94,Thrillers,Movie,5.3,15464.0
...,...,...,...,...,...,...,...,...,...,...,...
2290,s8242,The CEO,Kunle Afolayan,Nigeria,2016,TV-14,109,"Dramas, International Movies, Thrillers",Movie,5.7,121.0
2291,s8310,The Foreigner,Martin Campbell,"United Kingdom, China, United States, India",2017,R,113,"Action & Adventure, International Movies",Movie,7.0,112487.0
2292,s8315,The Frozen Ground,Scott Walker,United States,2013,R,106,"Dramas, Thrillers",Movie,6.4,62183.0
2293,s8321,The Girl with the Dragon Tattoo,David Fincher,"United States, Sweden, Norway",2011,R,158,"Dramas, Thrillers",Movie,7.8,454917.0
2294,s8707,We the Animals,Jeremiah Zagar,United States,2018,R,93,"Dramas, Independent Movies",Movie,6.9,4181.0

In [18]:
#save the merged Data Frame as 'Merged_Netflix_movie&rating.csv' for analysis
title_rating_df.to_csv("Merged_Netflix_movie&rating.csv", index=False)